### ISSUE TITLE
Add lightning warnings

### ISSUE THREAD

**Issue by metbril** [metbril/home-assistant-config#43]
https://github.com/pinkywafer/Home-Assistant_Config/blob/master/packages/weather/lightning_warnings.yaml

**Comment by CCOSTAN** [comment]
https://www.youtube.com/watch?v=jwnovbXCrGY

You will love the integration.  Super easy to set up and use.

**Comment by metbril** [comment]
I already use the integration. Mainly as a map in the UI and some entities. What I will add are automations with warnings.
